name: unit-test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Hardhat unit test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command
